//! Loading 
export const SET_IS_LOADING = "SET_IS_LOADING";

//! Skill
export const GET_SKILL = "GET_SKILL";
export const SET_SKILL = "SET_SKILL";
export const CREATE_SKILL = "CREATE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";

//! Sub Skill
export const GET_SUB_SKILL = "GET_SUB_SKILL";
export const SET_SUB_SKILL = "SET_SUB_SKILL";
export const CREATE_SUB_SKILL = "CREATE_SUB_SKILL";
export const UPDATE_SUB_SKILL = "UPDATE_SUB_SKILL";
export const DELETE_SUB_SKILL = "DELETE_SUB_SKILL";

//! Example
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

//! Partner
export const GET_ALL_PARTNER = "GET_ALL_PARTNER";
export const SET_ALL_PARTNER = "GET_ALL_PARTNER";
export const GET_ACTIVE_PARTNER = "GET_ACTIVE_PARTNER";
export const SET_ACTIVE_PARTNER = "GET_ACTIVE_PARTNER";
export const GET_BANNED_PARTNER = "GET_BANNED_PARTNER";
export const SET_BANNED_PARTNER = "GET_BANNED_PARTNER";