//! Loading 
export const SET_IS_LOADING = "SET_IS_LOADING";

//! Partner
export const GET_ALL_PARTNER = "GET_ALL_PARTNER";
export const SET_ALL_PARTNER = "GET_ALL_PARTNER";
export const GET_ACTIVE_PARTNER = "GET_ACTIVE_PARTNER";
export const SET_ACTIVE_PARTNER = "GET_ACTIVE_PARTNER";
export const GET_BANNED_PARTNER = "GET_BANNED_PARTNER";
export const SET_BANNED_PARTNER = "GET_BANNED_PARTNER";
export const GET_PARTNER_BY_ID = "GET_PARTNER_BY_ID";
export const SET_PARTNER_BY_ID = "SET_PARTNER_BY_ID";
export const CHANGE_PARTNER_STATUS = "CHANGE_PARTNER_STATUS";
export const CHANGE_PARTNER_KYC_STATUS = "CHANGE_PARTNER_KYC_STATUS";
export const UPDATE_PARTNER = "UPDATE_PARTNER";
export const DELETE_PARTNER = "DELETE_PARTNER";
export const GET_PARTNER_WORK = "GET_PARTNER_WORK";
export const DELETE_PARTNER_WORK_BY_ID = "DELETE_PARTNER_WORK_BY_ID";

//! User
export const GET_ALL_USER = "GET_ALL_USER";
export const SET_ALL_USER = "GET_ALL_USER";
export const GET_ACTIVE_USER = "GET_ACTIVE_USER";
export const SET_ACTIVE_USER = "GET_ACTIVE_USER";
export const GET_BANNED_USER = "GET_BANNED_USER";
export const SET_BANNED_USER = "GET_BANNED_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const SET_USER_BY_ID = "SET_USER_BY_ID";
export const CHANGE_USER_STATUS = "CHANGE_USER_STATUS";
export const CHANGE_USER_KYC_STATUS = "CHANGE_USER_KYC_STATUS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

//! Skill
export const GET_SKILL = "GET_SKILL";
export const SET_SKILL = "SET_SKILL";
export const CREATE_SKILL = "CREATE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";

//! Sub Skill
export const GET_SUB_SKILL = "GET_SUB_SKILL";
export const SET_SUB_SKILL = "SET_SUB_SKILL";
export const CREATE_SUB_SKILL = "CREATE_SUB_SKILL";
export const UPDATE_SUB_SKILL = "UPDATE_SUB_SKILL";
export const DELETE_SUB_SKILL = "DELETE_SUB_SKILL";