export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

//! Loading 
export const SET_IS_LOADING = "SET_IS_LOADING";

//! Skill
export const GET_SKILL = "GET_SKILL";
export const SET_SKILL = "SET_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";


export const CREATE_SKILL = "CREATE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";